version: "3.7"

volumes: 
  db:

networks:
  frontend:
  backend:

services: 
  web:
    image: moodstats/frontend
    build: .
    restart: on-failure
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mood.entrypoints=http"
      - "traefik.http.routers.mood.rule=Host(`mood.ennen.dev`)"
      - "traefik.http.routers.mood.middlewares=https-redirect@file"
      - "traefik.http.routers.mood-secure.entrypoints=https"
      - "traefik.http.routers.mood-secure.rule=Host(`mood.ennen.dev`)"
      - "traefik.http.routers.mood-secure.tls=true"
      - "traefik.http.routers.mood-secure.tls.certresolver=http"
      - "traefik.http.routers.mood-secure.service=mood"
      - "traefik.http.routers.mood-secure.middlewares=default-headers@file"
      - "traefik.http.services.mood.loadbalancer.server.port=80"
      - "traefik.docker.network=docker-network"
